export const Materials = {
  0: 'Asphalt',
  1: 'Brick',
  2: 'Iron',
  3: 'Ceramic',
  4: 'Concrete',
  5: 'Steel',
  6: 'PVC',
  7: 'Other',
};

export const Shapes = {
  0: 'Circle',
  1: 'Ellipse',
  2: 'Rectangle',
  3: 'Trapezoid',
  4: 'Other',
};

export const TimeZones = {
  0: 'America/Puerto_Rico',
  1: 'America/New_York',
  2: 'America/Chicago',
  3: 'America/Denver',
  4: 'America/Phoenix',
  5: 'America/Los_Angeles',
  6: 'America/Anchorage',
  7: 'Pacific/Honolulu',
};

export const States = {
  AL: 'Alabama',
  AK: 'Alaska',
  AZ: 'Arizona',
  AR: 'Arkansas',
  CA: 'California',
  CO: 'Colorado',
  CT: 'Connecticut',
  DE: 'Delaware',
  DC: 'District Of Columbia',
  FL: 'Florida',
  GA: 'Georgia',
  HI: 'Hawaii',
  ID: 'Idaho',
  IL: 'Illinois',
  IN: 'Indiana',
  IA: 'Iowa',
  KS: 'Kansas',
  KY: 'Kentucky',
  LA: 'Louisiana',
  ME: 'Maine',
  MD: 'Maryland',
  MA: 'Massachusetts',
  MI: 'Michigan',
  MN: 'Minnesota',
  MS: 'Mississippi',
  MO: 'Missouri',
  MT: 'Montana',
  NE: 'Nebraska',
  NV: 'Nevada',
  NH: 'New Hampshire',
  NJ: 'New Jersey',
  NM: 'New Mexico',
  NY: 'New York',
  NC: 'North Carolina',
  ND: 'North Dakota',
  OH: 'Ohio',
  OK: 'Oklahoma',
  OR: 'Oregon',
  PA: 'Pennsylvania',
  RI: 'Rhode Island',
  SC: 'South Carolina',
  SD: 'South Dakota',
  TN: 'Tennessee',
  TX: 'Texas',
  UT: 'Utah',
  VT: 'Vermont',
  VI: 'Virgin Islands',
  VA: 'Virginia',
  WA: 'Washington',
  WV: 'West Virginia',
  WI: 'Wisconsin',
  WY: 'Wyoming',
};
